/*
 * Icon — the kebab-case lucide registry.
 *
 * The comp authors icon names as kebab-case strings in its data ("graduation-cap",
 * "circle-dot", …), and the ported screens keep those strings so a record can
 * still say which icon it wants. This registry maps every name the comp uses —
 * all 121 of them, extracted from the comp and checked against the package —
 * to its `lucide-react` component.
 *
 * Imports are explicit so the bundle only carries the icons the app actually
 * uses; `lucide-react` ships well over a thousand. An unknown name renders
 * `Circle` rather than throwing, so a typo degrades instead of blanking a
 * screen. Need one that is not here? Add the import and one registry line.
 */

import {
  Circle,
  Activity,
  AppWindow,
  ArrowBigUp,
  ArrowLeft,
  ArrowRight,
  Award,
  BadgeCheck,
  Banknote,
  BarChart3,
  Bell,
  BookOpen,
  Bookmark,
  BookmarkX,
  Briefcase,
  Building2,
  Calendar,
  CalendarArrowUp,
  CalendarCheck,
  CalendarClock,
  CalendarCog,
  CalendarDays,
  CalendarPlus,
  Check,
  CheckCheck,
  CheckCircle2,
  ChevronRight,
  Chrome,
  CircleDot,
  Clapperboard,
  ClipboardCheck,
  ClipboardList,
  Clock,
  CloudOff,
  Copy,
  CreditCard,
  Download,
  EyeOff,
  FileCheck,
  FileText,
  FileType,
  Film,
  Flag,
  Flame,
  FolderClock,
  GitBranch,
  GitCompare,
  GraduationCap,
  GripVertical,
  Hand,
  Heart,
  HeartHandshake,
  Hourglass,
  Infinity,
  Info,
  Landmark,
  Languages,
  LayoutGrid,
  Link,
  Linkedin,
  ListChecks,
  ListTree,
  Lock,
  Mail,
  MapPin,
  Maximize,
  Medal,
  Megaphone,
  Menu,
  MessageCircleQuestion,
  MessageCircleReply,
  MessageSquare,
  MessageSquareDashed,
  MessageSquareText,
  MessageSquareWarning,
  Minus,
  NotebookPen,
  Orbit,
  Paperclip,
  Pause,
  PenLine,
  PenTool,
  Pencil,
  Percent,
  Pin,
  Play,
  Plus,
  Presentation,
  Quote,
  Radio,
  Receipt,
  RefreshCw,
  Repeat2,
  RotateCcw,
  Search,
  SearchX,
  Send,
  Settings2,
  Share2,
  ShieldCheck,
  Snowflake,
  Sparkles,
  Sprout,
  Star,
  Sunrise,
  Target,
  ThumbsUp,
  Timer,
  Trash2,
  TriangleAlert,
  Trophy,
  Type,
  Unlock,
  UserRound,
  UserRoundCheck,
  UserRoundSearch,
  Users,
  UsersRound,
  Video,
  Wand2,
  WifiOff,
  X,
  XCircle,
} from "lucide-react";
import type { LucideIcon } from "lucide-react";

export const ICONS: Record<string, LucideIcon> = {
  "activity": Activity,
  "app-window": AppWindow,
  "arrow-big-up": ArrowBigUp,
  "arrow-left": ArrowLeft,
  "arrow-right": ArrowRight,
  "award": Award,
  "badge-check": BadgeCheck,
  "banknote": Banknote,
  "bar-chart-3": BarChart3,
  "bell": Bell,
  "book-open": BookOpen,
  "bookmark": Bookmark,
  "bookmark-x": BookmarkX,
  "briefcase": Briefcase,
  "building-2": Building2,
  "calendar": Calendar,
  "calendar-arrow-up": CalendarArrowUp,
  "calendar-check": CalendarCheck,
  "calendar-clock": CalendarClock,
  "calendar-cog": CalendarCog,
  "calendar-days": CalendarDays,
  "calendar-plus": CalendarPlus,
  "check": Check,
  "check-check": CheckCheck,
  "check-circle-2": CheckCircle2,
  "chevron-right": ChevronRight,
  "chrome": Chrome,
  "circle-dot": CircleDot,
  "clapperboard": Clapperboard,
  "clipboard-check": ClipboardCheck,
  "clipboard-list": ClipboardList,
  "clock": Clock,
  "cloud-off": CloudOff,
  "copy": Copy,
  "credit-card": CreditCard,
  "download": Download,
  "eye-off": EyeOff,
  "file-check": FileCheck,
  "file-text": FileText,
  "file-type": FileType,
  "film": Film,
  "flag": Flag,
  "flame": Flame,
  "folder-clock": FolderClock,
  "git-branch": GitBranch,
  "git-compare": GitCompare,
  "graduation-cap": GraduationCap,
  "grip-vertical": GripVertical,
  "hand": Hand,
  "heart": Heart,
  "heart-handshake": HeartHandshake,
  "hourglass": Hourglass,
  "infinity": Infinity,
  "info": Info,
  "landmark": Landmark,
  "languages": Languages,
  "layout-grid": LayoutGrid,
  "link": Link,
  "linkedin": Linkedin,
  "list-checks": ListChecks,
  "list-tree": ListTree,
  "lock": Lock,
  "mail": Mail,
  "map-pin": MapPin,
  "maximize": Maximize,
  "medal": Medal,
  "megaphone": Megaphone,
  "menu": Menu,
  "message-circle-question": MessageCircleQuestion,
  "message-circle-reply": MessageCircleReply,
  "message-square": MessageSquare,
  "message-square-dashed": MessageSquareDashed,
  "message-square-text": MessageSquareText,
  "message-square-warning": MessageSquareWarning,
  "minus": Minus,
  "notebook-pen": NotebookPen,
  "orbit": Orbit,
  "paperclip": Paperclip,
  "pause": Pause,
  "pen-line": PenLine,
  "pen-tool": PenTool,
  "pencil": Pencil,
  "percent": Percent,
  "pin": Pin,
  "play": Play,
  "plus": Plus,
  "presentation": Presentation,
  "quote": Quote,
  "radio": Radio,
  "receipt": Receipt,
  "refresh-cw": RefreshCw,
  "repeat-2": Repeat2,
  "rotate-ccw": RotateCcw,
  "search": Search,
  "search-x": SearchX,
  "send": Send,
  "settings-2": Settings2,
  "share-2": Share2,
  "shield-check": ShieldCheck,
  "snowflake": Snowflake,
  "sparkles": Sparkles,
  "sprout": Sprout,
  "star": Star,
  "sunrise": Sunrise,
  "target": Target,
  "thumbs-up": ThumbsUp,
  "timer": Timer,
  "trash-2": Trash2,
  "triangle-alert": TriangleAlert,
  "trophy": Trophy,
  "type": Type,
  "unlock": Unlock,
  "user-round": UserRound,
  "user-round-check": UserRoundCheck,
  "user-round-search": UserRoundSearch,
  "users": Users,
  "users-round": UsersRound,
  "video": Video,
  "wand-2": Wand2,
  "wifi-off": WifiOff,
  "x": X,
  "x-circle": XCircle,
};

export interface IconProps {
  /** Kebab-case lucide name, e.g. "graduation-cap". */
  name: string;
  /** Edge length in px. */
  size?: number;
  /** Any CSS colour; defaults to `currentColor`. */
  color?: string;
  strokeWidth?: number;
  className?: string;
}

/**
 * `<Icon name="graduation-cap" size={18} />`
 *
 * Everything is sized in px because the comp sizes icons in px; colour is left
 * to `currentColor` unless a caller needs a tint that is not the text colour.
 */
export function Icon({ name, size = 18, color, strokeWidth = 2, className }: IconProps) {
  const Cmp = ICONS[name] ?? Circle;
  return (
    <Cmp
      size={size}
      color={color}
      strokeWidth={strokeWidth}
      className={className}
      aria-hidden="true"
      focusable="false"
    />
  );
}

export default Icon;
